import {Database,Search,Code2,LogIn,X,Loader2} from 'lucide-react'; import {useState} from 'react'; import {orkgConnect,orkgSearch,sparql} from '@/services/api'; import type {OrkgSearchResult,SparqlResult} from '@/types';

function itemTitle(i:any){return String(i?.title||i?.label||i?.name||i?.id||'Ressource ORKG')}
function toYear(i:any){const y=i?.year??i?.publication_year;return typeof y==='number'?y:(typeof y==='string'&&/^\\d{4}$/.test(y)?Number(y):null)}
export function OrkgPanel({onUseQuery,onClose}:{onUseQuery:(q:string)=>void;onClose:()=>void}){
 const [tab,setTab]=useState<'search'|'sparql'|'connect'>('search'); const [q,setQ]=useState(''); const [size,setSize]=useState(20); const [data,setData]=useState<OrkgSearchResult|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const [query,setQuery]=useState('SELECT ?s ?p ?o WHERE { ?s ?p ?o } LIMIT 20'); const [sparqlData,setSparqlData]=useState<SparqlResult|null>(null);
 const [user,setUser]=useState('');const [pass,setPass]=useState('');const [connected,setConnected]=useState<number|null>(null);
 async function search(){if(!q.trim())return;setLoading(true);setError('');try{setData(await orkgSearch(q.trim(),size))}catch(e){setError(e instanceof Error?e.message:'Recherche ORKG impossible.')}finally{setLoading(false)}}
 async function run(){setLoading(true);setError('');try{setSparqlData(await sparql(query,size))}catch(e){setError(e instanceof Error?e.message:'Requête SPARQL refusée ou indisponible.')}finally{setLoading(false)}}
 async function connect(){setLoading(true);setError('');try{const r=await orkgConnect(user,pass);setConnected(r.expires_in)}catch(e){setError(e instanceof Error?e.message:'Connexion ORKG impossible.')}finally{setLoading(false)}}
 return <div className="fixed inset-0 z-40 bg-black/70 p-4 backdrop-blur"><div className="mx-auto flex h-full max-w-5xl flex-col rounded-2xl border border-slate-700 bg-slate-900 shadow-2xl">
  <header className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><h2 className="flex items-center gap-2 font-semibold"><Database size={18} className="text-emerald-400"/>ORKG</h2><p className="text-xs text-slate-400">Recherche de ressources et SPARQL en lecture seule via Research_Gen.</p></div><button onClick={onClose}><X/></button></header>
  <nav className="flex gap-1 border-b border-slate-800 px-4 py-2"><button className={tab==='search'?'tab active':'tab'} onClick={()=>setTab('search')}><Search size={14}/>Recherche</button><button className={tab==='sparql'?'tab active':'tab'} onClick={()=>setTab('sparql')}><Code2 size={14}/>SPARQL</button><button className={tab==='connect'?'tab active':'tab'} onClick={()=>setTab('connect')}><LogIn size={14}/>Connexion ORKG</button></nav>
  <div className="min-h-0 flex-1 overflow-auto p-5">
   {tab==='search'&&<><div className="flex flex-wrap gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()} placeholder="Rechercher des ressources ORKG…" className="field flex-1"/><select value={size} onChange={e=>setSize(Number(e.target.value))} className="field w-24"><option>10</option><option>20</option><option>50</option><option>100</option></select><button onClick={()=>void search()} disabled={loading||!q.trim()} className="primary w-auto px-4">{loading?<Loader2 className="animate-spin"/>:<Search size={15}/>}Rechercher</button></div>
    {data&&<div className="mt-5"><div className="mb-3 flex items-center justify-between"><span className="text-sm text-slate-300">{data.total} résultat(s) pour « {data.query} »</span><button onClick={()=>onUseQuery(data.query)} className="secondary">Utiliser cette recherche pour la revue</button></div><div className="grid gap-2">{data.items.map((i,idx)=><div key={String(i.id||idx)} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><div className="font-medium">{itemTitle(i)}</div><div className="mt-1 text-xs text-slate-400">{toYear(i)??'Année inconnue'} {i.doi?`· DOI ${i.doi}`:''} {i.id?`· ${i.id}`:''}</div>{(i.abstract||i.description)&&<p className="mt-2 line-clamp-3 text-xs leading-relaxed text-slate-400">{String(i.abstract||i.description)}</p>}</div>)}</div></div>}
   </>}
   {tab==='sparql'&&<><textarea value={query} onChange={e=>setQuery(e.target.value)} rows={7} className="field font-mono text-xs"/><div className="mt-2 flex gap-2"><button onClick={()=>void run()} disabled={loading} className="primary w-auto px-4">{loading?<Loader2 className="animate-spin"/>:<Code2 size={15}/>}Exécuter</button><span className="self-center text-xs text-slate-500">Lecture seule · LIMIT contrôlé par le backend.</span></div>{sparqlData&&<div className="mt-4 overflow-auto rounded-xl border border-slate-800"><table className="min-w-full text-xs"><thead>{<tr>{sparqlData.columns.map(c=><th key={c} className="border-b border-slate-800 px-3 py-2 text-left">{c}</th>)}</tr>}</thead><tbody>{sparqlData.rows.map((r,i)=><tr key={i}>{sparqlData.columns.map(c=><td key={c} className="border-b border-slate-900 px-3 py-2 text-slate-300">{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'')}</td>)}</tr>)}</tbody></table></div>}</>}
   {tab==='connect'&&<div className="max-w-md"><p className="mb-4 text-sm text-slate-300">Connexion ORKG via OIDC. Les identifiants sont transmis au backend, qui stocke le jeton chiffré.</p><label className="label">Nom d’utilisateur<input value={user} onChange={e=>setUser(e.target.value)} className="field"/></label><label className="label">Mot de passe<input type="password" value={pass} onChange={e=>setPass(e.target.value)} className="field"/></label><button onClick={()=>void connect()} disabled={loading||!user||!pass} className="primary w-auto px-4">{loading?<Loader2 className="animate-spin"/>:<LogIn size={15}/>}Se connecter</button>{connected!==null&&<p className="mt-3 text-xs text-emerald-300">Connecté à ORKG. Session valable environ {Math.round(connected/60)} min.</p>}</div>}
   {error&&<p className="mt-4 error">{error}</p>}
  </div>
 </div></div>
}
