import {useState} from 'react'; import {BookOpen,Download,Eye,Loader2,ChevronDown,ChevronUp} from 'lucide-react'; import type {ReviewOut} from '@/types'; import {exportReview,getPreview} from '@/services/api'; import {downloadBlob} from '@/utils/helpers';
export function ReviewCard({review}:{review:ReviewOut}){
 const [preview,setPreview]=useState(''); const [busy,setBusy]=useState(false); const [sourcesOpen,setSourcesOpen]=useState(false);
 async function previewIt(){setBusy(true);try{const p=await getPreview(review.id);setPreview(p.html)}catch(e){alert(e instanceof Error?e.message:'Preview indisponible.')}finally{setBusy(false)}}
 async function dl(f:'md'|'docx'|'pdf'){setBusy(true);try{const x=await exportReview(review.id,f);downloadBlob(x.blob,x.filename)}catch(e){alert(e instanceof Error?e.message:'Export impossible.')}finally{setBusy(false)}}
 return <div className="mt-3 overflow-hidden rounded-2xl border border-emerald-500/20 bg-slate-950/40">
  <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 p-3"><div><div className="flex items-center gap-2 text-sm font-medium"><BookOpen size={15} className="text-emerald-400"/>Revue de littérature</div><div className="mt-1 text-xs text-slate-500">Provider: {review.provider} · modèle: {review.model}</div></div><div className="flex gap-1.5"><button onClick={()=>void previewIt()} className="secondary">{busy?<Loader2 size={13} className="animate-spin"/>:<Eye size={13}/>}Prévisualiser</button>{(['md','docx','pdf'] as const).map(f=><button key={f} onClick={()=>void dl(f)} className="secondary"><Download size={13}/>{f.toUpperCase()}</button>)}</div></div>
  <article className="prose-review p-4">{review.structured?.sections?.length?review.structured.sections.map((s,i)=><section key={i}><h3>{s.heading}</h3><p>{s.content}</p></section>):<pre>{review.content_md}</pre>}</article>
  <div className="border-t border-slate-800 p-3"><button onClick={()=>setSourcesOpen(!sourcesOpen)} className="flex items-center gap-2 text-xs text-slate-300">{sourcesOpen?<ChevronUp size={14}/>:<ChevronDown size={14}/>}Sources et citations ({review.structured?.sources?.length||0})</button>{sourcesOpen&&<div className="mt-3 grid gap-2">{(review.structured?.sources||[]).map(s=><div key={s.index} className="rounded-lg bg-slate-900 p-2 text-xs"><b>[{s.index}] {s.title}</b><div className="text-slate-500">{s.authors?.join(', ')} {s.year?`· ${s.year}`:''} {s.doi?`· DOI ${s.doi}`:''}</div></div>)}</div>}</div>
  {preview&&<div className="border-t border-slate-800 bg-white p-5 text-slate-900"><div className="mb-2 flex justify-between"><span className="text-xs font-semibold uppercase text-slate-500">Preview HTML sécurisé par le backend</span><button onClick={()=>setPreview('')} className="text-xs text-slate-500">Fermer</button></div><div dangerouslySetInnerHTML={{__html:preview}}/></div>}
 </div>
}