import {useCallback,useEffect,useState} from 'react'; import {createReview,getApiKey,getReview,listModels,pollJob,uploadDocument} from '@/services/api'; import type {BackendModel,ChatMessage,PendingDocument,ReviewCreatePayload} from '@/types'; import {guessKind} from '@/data/formats'; import {uid} from '@/utils/helpers';
export function useResearch(){
 const [models,setModels]=useState<BackendModel[]>([]); const [defaultModel,setDefaultModel]=useState(''); const [selected,setSelected]=useState(''); const [loadingModels,setLoadingModels]=useState(true); const [modelError,setModelError]=useState('');
 const [docs,setDocs]=useState<PendingDocument[]>([]); const [messages,setMessages]=useState<ChatMessage[]>([]); const [sending,setSending]=useState(false); const [job,setJob]=useState<{status:string;progress:number}|null>(null);
 const refreshModels=useCallback(async()=>{setLoadingModels(true);setModelError('');try{const d=await listModels();setModels(d.providers);setDefaultModel(d.default);setSelected(cur=>d.providers.some(x=>x.key===cur)?cur:d.default)}catch(e){setModelError(e instanceof Error?e.message:'Impossible de charger les modèles.')}finally{setLoadingModels(false)}},[]);
 useEffect(()=>{if(getApiKey())void refreshModels();else{setLoadingModels(false)}},[refreshModels]);
 const addFiles=useCallback(async(files:FileList|File[])=>{for(const file of Array.from(files)){const item:PendingDocument={id:uid(),file,name:file.name,kind:guessKind(file.name),size:file.size,status:'uploading'};setDocs(x=>[...x,item]);try{const d=await uploadDocument(file);setDocs(x=>x.map(v=>v.id===item.id?{...v,status:d.status==='parsed'?'parsed':'failed',document:d,error:d.error}:v))}catch(e){setDocs(x=>x.map(v=>v.id===item.id?{...v,status:'failed',error:e instanceof Error?e.message:'Upload impossible'}:v))}}},[]);
 const removeDoc=(id:string)=>setDocs(x=>x.filter(d=>d.id!==id));
 const send=useCallback(async(topic:string,instructions:string,orkgQuery:string,orkgSize:number,maxTokens:number)=>{if(!topic.trim()||sending||!selected)return;const valid=docs.filter(d=>d.status==='parsed'&&d.document?.id);setMessages(m=>[...m,{id:uid(),role:'user',text:topic.trim(),createdAt:Date.now(),status:'sent',provider:selected,documents:docs.map(d=>({id:d.id,name:d.name,kind:d.kind,status:d.status,size:d.size}))}]);setDocs([]);setSending(true);setJob({status:'queued',progress:0});
 const payload:ReviewCreatePayload={topic:topic.trim(),provider:selected,instructions:instructions.trim()||undefined,document_ids:valid.map(d=>d.document!.id),orkg_query:orkgQuery.trim()||undefined,orkg_size:orkgQuery.trim()?orkgSize:undefined,max_tokens:maxTokens||undefined};
 try{const j=await createReview(payload);setJob({status:j.status,progress:j.progress});const done=await pollJob(j.id,x=>setJob({status:x.status,progress:x.progress}));const reviewId=done.result.review_id as string;if(!reviewId)throw new Error('Le job est terminé sans review_id.');const review=await getReview(reviewId);setMessages(m=>[...m,{id:uid(),role:'assistant',text:review.content_md,createdAt:Date.now(),status:'sent',provider:review.provider,model:review.model,review}]);}catch(e){setMessages(m=>[...m,{id:uid(),role:'assistant',text:e instanceof Error?e.message:'Une erreur inconnue est survenue.',createdAt:Date.now(),status:'error'}]);}finally{setSending(false);setJob(null)}},[docs,selected,sending]);
 return {models,defaultModel,selected,setSelected,loadingModels,modelError,refreshModels,docs,addFiles,removeDoc,messages,sending,job,send};
}
