import {useRef,useState} from 'react'; import {Paperclip,SlidersHorizontal,Send,BookOpen,Search} from 'lucide-react'; import {AppShell} from '@/components/AppShell'; import {ApiKeyDialog} from '@/components/ApiKeyDialog'; import {OrkgPanel} from '@/components/OrkgPanel'; import {DocumentList} from '@/components/DocumentList'; import {ReviewCard} from '@/components/ReviewCard'; import {useResearch} from '@/hooks/useResearch'; import {getApiKey} from '@/services/api'; import {ACCEPT} from '@/data/formats';

export default function App(){
 const r=useResearch(); const [apiOpen,setApiOpen]=useState(!getApiKey()); const [orkgOpen,setOrkgOpen]=useState(false); const [topic,setTopic]=useState(''); const [instructions,setInstructions]=useState(''); const [orkgQuery,setOrkgQuery]=useState(''); const [orkgSize,setOrkgSize]=useState(20); const [maxTokens,setMaxTokens]=useState(1500); const [advanced,setAdvanced]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const send=()=>{if(!topic.trim()||r.sending||!r.selected)return;r.send(topic,instructions,orkgQuery,orkgSize,maxTokens);setTopic('')};
 return <AppShell models={r.models} selected={r.selected} onSelect={r.setSelected} loading={r.loadingModels} onRefresh={()=>void r.refreshModels()} onApiKey={()=>setApiOpen(true)} onOrkg={()=>setOrkgOpen(true)}>
  <div className="mx-auto grid max-w-7xl gap-5 px-4 py-5 lg:grid-cols-[minmax(0,1fr)_320px]">
   <section className="min-w-0">
    <div className="mb-5 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-emerald-400/10 p-2 text-emerald-400"><BookOpen size={20}/></div><div><h2 className="text-lg font-semibold">Générer une revue de littérature</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-slate-400">Définissez le sujet, ajoutez des sources CSV/XLSX/PDF/JSON et, si nécessaire, utilisez une recherche ORKG. Research_Gen assemble les sources, génère la revue de façon asynchrone et conserve les citations.</p></div></div></div>
    <div className="space-y-4">{r.messages.length===0?<div className="rounded-2xl border border-dashed border-slate-800 p-8 text-center text-sm text-slate-500">Aucune revue générée. Commencez par un sujet ou ajoutez vos sources.</div>:r.messages.map(m=><div key={m.id} className={`rounded-2xl border p-4 ${m.role==='user'?'border-emerald-500/20 bg-emerald-500/5':'border-slate-800 bg-slate-900/50'}`}><div className="mb-2 text-[11px] uppercase tracking-wide text-slate-500">{m.role==='user'?'Sujet soumis':'Résultat Research_Gen'}</div>{m.role==='user'?<><div className="text-sm">{m.text}</div>{m.documents?.length&&<div className="mt-2 text-xs text-slate-500">{m.documents.length} document(s) joint(s)</div>}</>:m.review?<ReviewCard review={m.review}/>:<p className="text-sm text-red-300">{m.text}</p>}</div>)}</div>
    {r.sending&&r.job&&<div className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3"><div className="flex justify-between text-xs"><span>Génération en cours</span><span>{r.job.progress}% · {r.job.status}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-emerald-400 transition-all" style={{width:`${r.job.progress}%`}}/></div></div>}
    <div className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><DocumentList items={r.docs} onRemove={r.removeDoc}/><div className="mt-3 flex items-end gap-2"><button onClick={()=>fileRef.current?.click()} disabled={r.sending} className="secondary h-11 w-11 p-0" title="Importer CSV, XLSX, PDF ou JSON"><Paperclip size={17}/></button><input ref={fileRef} type="file" multiple accept={ACCEPT} hidden onChange={e=>{if(e.target.files)void r.addFiles(e.target.files);e.currentTarget.value=''}}/><textarea value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows={2} disabled={r.sending} placeholder="Sujet de la revue de littérature…" className="field flex-1 resize-none"/><button onClick={send} disabled={r.sending||!topic.trim()||!r.selected||r.docs.some(d=>d.status==='uploading')} className="primary h-11 w-11 p-0"><Send size={17}/></button></div><div className="mt-2 flex items-center justify-between text-[11px] text-slate-500"><span>Entrée pour générer · Maj+Entrée pour une nouvelle ligne</span><button onClick={()=>setAdvanced(!advanced)} className="flex items-center gap-1 hover:text-slate-300"><SlidersHorizontal size={13}/>Options de génération</button></div>
     {advanced&&<div className="mt-3 grid gap-3 border-t border-slate-800 pt-3 md:grid-cols-3"><label className="label md:col-span-2">Instructions optionnelles<textarea maxLength={2000} rows={3} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Ex. Focus sur les méthodes depuis 2020 et garde la revue sous 500 mots." className="field resize-none"/></label><div className="space-y-3"><label className="label">Taille ORKG<select value={orkgSize} onChange={e=>setOrkgSize(Number(e.target.value))} className="field"><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option><option value={100}>100</option></select></label><label className="label">max_tokens<input type="number" min={64} max={8192} value={maxTokens} onChange={e=>setMaxTokens(Number(e.target.value))} className="field"/></label></div><label className="label md:col-span-3">Requête ORKG optionnelle<input maxLength={500} value={orkgQuery} onChange={e=>setOrkgQuery(e.target.value)} placeholder="Ex. knowledge graphs" className="field"/><span className="text-[11px] text-slate-500">Le backend exécutera cette recherche ORKG au moment de la génération.</span></label></div>}
    </div>
   </section>
   <aside className="space-y-4"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex items-center gap-2 text-sm font-medium"><Search size={15} className="text-emerald-400"/>Sources ORKG</div><p className="mt-2 text-xs leading-relaxed text-slate-500">Recherchez des ressources ORKG, consultez les résultats ou exécutez une requête SPARQL en lecture seule.</p><button onClick={()=>setOrkgOpen(true)} className="primary mt-3 w-full">Ouvrir la recherche ORKG</button>{orkgQuery&&<div className="mt-3 rounded-lg bg-slate-950 p-2 text-xs">Recherche sélectionnée : <b>{orkgQuery}</b></div>}</div></aside>
  </div>
  {apiOpen&&<ApiKeyDialog onClose={()=>setApiOpen(false)} onChanged={()=>void r.refreshModels()}/>}
  {orkgOpen&&<OrkgPanel onClose={()=>setOrkgOpen(false)} onUseQuery={q=>{setOrkgQuery(q);setOrkgOpen(false);setAdvanced(true)}}/>}
 </AppShell>
}